main: com.sereneoasis.Abilities
name: Abilities
author: Sujan
version: 1.0.0
api-version: '1.20'
depend: [ NDatabase, WorldGuard ]
commands:
  abilities:
    description: Your description
    usage: /<command>
    permission: abilities.command
    aliases: [ s, so ]